CREATE TABLE CUSTOMER
(
CID NUMBER(2) NOT NULL,
CUST_NAME VARCHAR(20) NOT NULL,
PRICE NUMBER(10,2) NOT NULL,
CONSTRAINT PID_PK PRIMARY KEY(PID),
CONSTRAINT PR_CH CHECK(PRICE > 100)
);

CREATE TABLE CUSTOMER
(
PID NUMBER(2) NOT NULL,
PNAME VARCHAR(20) NOT NULL,
PRICE NUMBER(10,2) NOT NULL,
CONSTRAINT PID_PK PRIMARY KEY(PID),
CONSTRAINT PR_CH CHECK(PRICE > 100)
);

DESC CUSTOMER


--To check the constraints
SELECT *
FROM USER_CONSTRAINTS;

--for particular 
SELECT CONSTRAINT_NAME, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'CUSTOMER';


--**********************RENAME*************************
RENAME CUSTOMER TO CUSTOM;
DESC CUSTOM ;

--**********************ALTER*************************
--Add Col
ALTER TABLE CUSTOM 
ADD CID NUMBER(2);

--Drop Col
ALTER TABLE CUSTOM
DROP COLUMN CID;

--Change the data type
ALTER TABLE CUSTOM
MODIFY PNAME CHAR(40);
DESC CUSTOM;

--To Change Constraints null/not null
ALTER TABLE CUSTOM
MODIFY PNAME CHAR(40) NULL;

--To Rename the column
ALTER TABLE CUSTOM
RENAME COLUMN PNAME TO PRODUCT_NAME;
DESC CUSTOM;

--CREATING TWO TABLES
CREATE TABLE CUSTOM(
CID NUMBER(2) NOT NULL, 
CUST_NAME CHAR(40),
PID NUMBER(2) NOT NULL,
CONSTRAINT PID_FK FOREIGN KEY (PID) 
REFERENCES PRODUCT(PID)
);

CREATE TABLE PRODUCT (
PID NUMBER(2) NOT NULL, 
PNAME VARCHAR2(20) NOT NULL,
PRICE NUMBER(10, 2) NOT NULL,
CONSTRAINT PID_PK PRIMARY KEY (PID)
);
drop table product;
DESC CUSTOM;
DESC PRODUCT;

